/**
 * Monster sprites extracted from reference-img/monster-sprites/.
 * Auto-generated by scripts/extract-sprites.ts.
 * Flying monsters: 8 lines above bottom edge.
 * Ground monsters: 2 lines above bottom edge.
 */

export interface Monster {
  name: string;
  sprite: string[];
  palette: Record<string, [number, number, number]>;
  hp: number;
  xp: number;
  flying: boolean;
}

const RESET = "\x1b[0m";

const ALL_MONSTERS: Monster[] = [
  {
    name: "Hyperparameter Ranger",
    hp: 15, xp: 10,
    flying: false,
    palette: {
      "A": [0, 135, 81],
      "B": [0, 228, 54],
      "C": [171, 82, 54],
      "D": [255, 241, 232],
      "E": [194, 195, 199],
      "F": [255, 204, 170],
      "G": [0, 0, 0],
      "H": [29, 43, 83],
    },
    sprite: [
      "AAAABC  ",
      " AAAABC ",
      "DEFGFG C",
      "CHHHHH D",
      "CHHHABAD",
      " HAAAB C",
      " CC C C ",
    ],
  },
  {
    name: "Lord Vanishing",
    hp: 17, xp: 11,
    flying: false,
    palette: {
      "A": [29, 43, 83],
      "B": [255, 204, 170],
      "C": [0, 0, 0],
      "D": [41, 173, 255],
    },
    sprite: [
      " AAAA   ",
      "  AAAA  ",
      "AAAAAAAA",
      " BCBBC  ",
      " AABBADD",
      "AAAAAAAD",
      " AAAAA  ",
      " A   A  ",
    ],
  },
  {
    name: "Gandalf Hinton",
    hp: 20, xp: 13,
    flying: false,
    palette: {
      "A": [255, 204, 170],
      "B": [0, 0, 0],
      "C": [194, 195, 199],
      "D": [255, 241, 232],
      "E": [29, 43, 83],
    },
    sprite: [
      "  AAAA  ",
      " AAAAA  ",
      " AABAB  ",
      " CDDDD  ",
      " ACDDDA ",
      " EEEEE  ",
      " CADEA  ",
    ],
  },
  {
    name: "BERT Golem",
    hp: 22, xp: 14,
    flying: false,
    palette: {
      "A": [126, 37, 83],
      "B": [255, 0, 77],
      "C": [255, 204, 170],
      "D": [0, 0, 0],
      "E": [255, 236, 39],
      "F": [255, 163, 0],
    },
    sprite: [
      "  AAAB  ",
      " AAAAAB ",
      "AAAAAAA ",
      "AAACDCDE",
      "A ABBBBF",
      "  AAAAAF",
      "  AAAAAA",
      " AAAAAAF",
    ],
  },
  {
    name: "Sir Dropout",
    hp: 27, xp: 17,
    flying: false,
    palette: {
      "A": [255, 241, 232],
      "B": [194, 195, 199],
      "C": [255, 163, 0],
      "D": [0, 0, 0],
      "E": [255, 236, 39],
      "F": [126, 37, 83],
    },
    sprite: [
      "ABBBBBB ",
      "ABCCCCC ",
      "ABCDDDD ",
      "ABCCCDC ",
      "ABBBCEEE",
      "BFFFFEEC",
      "CAAAFFEC",
      " BB  BEE",
    ],
  },
  {
    name: "Baron Hallucinate",
    hp: 30, xp: 19,
    flying: false,
    palette: {
      "A": [29, 43, 83],
      "B": [255, 204, 170],
      "C": [0, 0, 0],
      "D": [255, 163, 0],
      "E": [126, 37, 83],
      "F": [255, 241, 232],
    },
    sprite: [
      "  AAAAA ",
      " AAAAAA ",
      " ABCBBC ",
      " DEEEBED",
      " AEEEAEA",
      " FEEEEEF",
      "F AA AF ",
    ],
  },
  {
    name: "Stochastic Sally",
    hp: 32, xp: 20,
    flying: false,
    palette: {
      "A": [171, 82, 54],
      "B": [95, 87, 79],
      "C": [255, 204, 170],
      "D": [0, 0, 0],
      "E": [0, 135, 81],
      "F": [255, 241, 232],
      "G": [0, 228, 54],
    },
    sprite: [
      " AAAAB  ",
      "AAAAAAB ",
      "AACDCD B",
      "AAEEFE F",
      "AAGEFEGF",
      "AAEEEE B",
      "A AA AB ",
    ],
  },
  {
    name: "Private Bias",
    hp: 35, xp: 22,
    flying: false,
    palette: {
      "A": [194, 195, 199],
      "B": [255, 241, 232],
      "C": [171, 82, 54],
      "D": [255, 163, 0],
      "E": [0, 0, 0],
      "F": [255, 204, 170],
      "G": [255, 0, 77],
      "H": [95, 87, 79],
    },
    sprite: [
      "A B B   ",
      "AAABBCCC",
      "AABABCCC",
      "AADBBEFE",
      "A DGBGGG",
      "  DHHHHH",
      " HDHHHHH",
      "  DCC C ",
    ],
  },
  {
    name: "Shadow Latent",
    hp: 37, xp: 23,
    flying: false,
    palette: {
      "A": [131, 118, 156],
      "B": [255, 163, 0],
      "C": [95, 87, 79],
      "D": [126, 37, 83],
    },
    sprite: [
      " AAAAA  ",
      " ABBBB  ",
      " AABBB  ",
      " CAAAA  ",
      "ACCCCCDD",
      " CAACAC ",
      " CA  AD ",
    ],
  },
  {
    name: "Sporacles Softmax",
    hp: 40, xp: 25,
    flying: false,
    palette: {
      "A": [255, 0, 77],
      "B": [255, 241, 232],
      "C": [255, 204, 170],
      "D": [0, 0, 0],
    },
    sprite: [
      "   AAA  ",
      "  ABABA ",
      " BAAAAAB",
      "  CCDCD ",
      "  AACCA ",
      " CAAACAC",
      "  C   C ",
    ],
  },
  {
    name: "Gelu Ooze",
    hp: 42, xp: 26,
    flying: false,
    palette: {
      "A": [0, 228, 54],
      "B": [0, 135, 81],
    },
    sprite: [
      "   AAA  ",
      "  BBBBA ",
      " BBAABA ",
      " BBBABA ",
      " BBBABA ",
      "BBBBBBBA",
    ],
  },
  {
    name: "Raspberry Pifiend",
    hp: 45, xp: 28,
    flying: false,
    palette: {
      "A": [0, 135, 81],
      "B": [171, 82, 54],
      "C": [126, 37, 83],
      "D": [255, 0, 77],
    },
    sprite: [
      "  AA B  ",
      "  CABB  ",
      " CDCBCD ",
      " CDDDDD ",
      " CDCCDC ",
      " CDDDDD ",
      "  CDDD  ",
      "  B  B  ",
    ],
  },
  {
    name: "Sssscalar Green",
    hp: 50, xp: 31,
    flying: false,
    palette: {
      "A": [0, 135, 81],
      "B": [0, 228, 54],
      "C": [255, 241, 232],
      "D": [95, 87, 79],
      "E": [171, 82, 54],
    },
    sprite: [
      "  AAAA  ",
      " AABAB  ",
      "CAAAAAA ",
      "CDDAAD  ",
      "ADDDDDA ",
      " EE E   ",
    ],
  },
  {
    name: "Basilissk Purple",
    hp: 52, xp: 32,
    flying: false,
    palette: {
      "A": [131, 118, 156],
      "B": [41, 173, 255],
      "C": [255, 241, 232],
      "D": [95, 87, 79],
      "E": [171, 82, 54],
    },
    sprite: [
      "  AAAA  ",
      " AABAB  ",
      "CAAAAAA ",
      "CDDDDDC ",
      "ADDDDDB ",
      "EAA A E ",
    ],
  },
  {
    name: "AARDMAx",
    hp: 55, xp: 34,
    flying: false,
    palette: {
      "A": [29, 43, 83],
      "B": [255, 163, 0],
      "C": [95, 87, 79],
      "D": [255, 241, 232],
      "E": [171, 82, 54],
    },
    sprite: [
      "  AAAAA ",
      " AABABAA",
      " AAAAAAA",
      "CAAA   A",
      "ACCCAD  ",
      "AEEEAEDD",
      " A A D  ",
    ],
  },
  {
    name: "Kermit Loss",
    hp: 57, xp: 35,
    flying: false,
    palette: {
      "A": [0, 135, 81],
      "B": [0, 228, 54],
      "C": [95, 87, 79],
      "D": [171, 82, 54],
    },
    sprite: [
      " AAAA   ",
      "AABAB   ",
      "AAAAAA  ",
      "CCCCCDD ",
      "CCCCDDDD",
      "DD D DD ",
    ],
  },
  {
    name: "Pincer Pruning",
    hp: 60, xp: 37,
    flying: false,
    palette: {
      "A": [126, 37, 83],
      "B": [255, 0, 77],
      "C": [255, 163, 0],
    },
    sprite: [
      " AB  BB ",
      "AB    BB",
      "ABC  CBB",
      " AABBAB ",
      "  BBBB  ",
      " A BB B ",
      "A A  B B",
    ],
  },
  {
    name: "Queen Thiccarus",
    hp: 62, xp: 38,
    flying: false,
    palette: {
      "A": [95, 87, 79],
      "B": [255, 204, 170],
      "C": [255, 241, 232],
    },
    sprite: [
      " ABB    ",
      "AAAAB   ",
      "AAAAAAAA",
      "ACAAABAB",
      "CAACAAAA",
      "C  C C C",
    ],
  },
  {
    name: "Cycloptimus",
    hp: 65, xp: 40,
    flying: false,
    palette: {
      "A": [95, 87, 79],
      "B": [131, 118, 156],
      "C": [194, 195, 199],
      "D": [255, 241, 232],
      "E": [29, 43, 83],
    },
    sprite: [
      "    AB  ",
      "   AB   ",
      "  AAAB  ",
      " ACDEDB ",
      " ACDEDA ",
      "  AAAA  ",
      "  A  B  ",
    ],
  },
  {
    name: "Fenrir GAN",
    hp: 67, xp: 41,
    flying: false,
    palette: {
      "A": [90, 90, 95],
      "B": [120, 120, 125],
      "C": [0, 0, 0],
    },
    sprite: [
      "   AB B ",
      "   AAAA ",
      " BBACAC ",
      "BAAABBBB",
      "AAAAAAAA",
      "A A B B ",
    ],
  },
  {
    name: "Echo Encoder",
    hp: 70, xp: 43,
    flying: false,
    palette: {
      "A": [126, 37, 83],
      "B": [255, 163, 0],
    },
    sprite: [
      "  A A   ",
      "AAABABAA",
      "AA AA AA",
      "A      A",
    ],
  },
  {
    name: "Antenna Dave",
    hp: 72, xp: 44,
    flying: false,
    palette: {
      "A": [255, 119, 168],
      "B": [255, 0, 77],
      "C": [126, 37, 83],
    },
    sprite: [
      "     A A",
      "BBB A A ",
      "CBBBBBB ",
      "CBBBCBC ",
      "ACABBBB ",
      "A  A  A ",
    ],
  },
  {
    name: "Python Constrictor",
    hp: 77, xp: 47,
    flying: false,
    palette: {
      "A": [95, 87, 79],
      "B": [171, 82, 54],
      "C": [255, 163, 0],
      "D": [255, 0, 77],
    },
    sprite: [
      "  ABBBB ",
      " ABBBCBC",
      " ABB BBB",
      " ABBB D ",
      "  ABBB D",
      "B   BBB ",
      "ABB BBB ",
      " ABBBB  ",
    ],
  },
  {
    name: "Cluckster Stopper",
    hp: 80, xp: 49,
    flying: false,
    palette: {
      "A": [255, 236, 39],
      "B": [255, 163, 0],
      "C": [194, 195, 199],
      "D": [180, 100, 30],
    },
    sprite: [
      "    A   ",
      "   BA   ",
      " CCBDDD ",
      "CCDDDDDD",
      "CCDBDDBD",
      "CCDDDDDD",
      " CCDDDD ",
      " B    B ",
    ],
  },
  {
    name: "Dead Neurons",
    hp: 85, xp: 52,
    flying: false,
    palette: {
      "A": [131, 118, 156],
      "B": [41, 173, 255],
      "C": [255, 241, 232],
    },
    sprite: [
      "  ABBB  ",
      " ABBBBB ",
      " ABCBBC ",
      " ABBBBB ",
      " ABBAAB ",
      "  ABBB  ",
      "   AB   ",
    ],
  },
  {
    name: "Squeaknet",
    hp: 87, xp: 53,
    flying: false,
    palette: {
      "A": [255, 119, 168],
      "B": [95, 87, 79],
      "C": [255, 163, 0],
    },
    sprite: [
      " A      ",
      "A  B B  ",
      " BBBCBC ",
      "BBBBBBBA",
      "B B B B ",
    ],
  },
  {
    name: "Ghoulash",
    hp: 90, xp: 55,
    flying: false,
    palette: {
      "A": [131, 118, 156],
      "B": [100, 60, 30],
    },
    sprite: [
      " ABBBB  ",
      "ABBABAB ",
      "ABBBBBB ",
      "AABBAB  ",
      " BAAAA  ",
      " BBBBAB ",
      " BAAAB  ",
      " B   B  ",
    ],
  },
  {
    name: "Slug Convergence",
    hp: 92, xp: 56,
    flying: false,
    palette: {
      "A": [95, 87, 79],
      "B": [0, 135, 81],
      "C": [131, 118, 156],
      "D": [255, 163, 0],
    },
    sprite: [
      " AA B B ",
      "ACAADBD ",
      "ACCBBB  ",
    ],
  },
  {
    name: "Noisy Bat",
    hp: 100, xp: 61,
    flying: true,
    palette: {
      "A": [95, 87, 79],
      "B": [255, 163, 0],
    },
    sprite: [
      "  A A   ",
      "AAABABAA",
      "AA AA AA",
      "A      A",
    ],
  },
  {
    name: "Condor Vulture",
    hp: 105, xp: 64,
    flying: true,
    palette: {
      "A": [30, 50, 120],
      "B": [95, 87, 79],
      "C": [255, 163, 0],
    },
    sprite: [
      " AA     ",
      "  AA    ",
      "AABA BB ",
      " AABBBCB",
      " BAABB B",
      "  BBB   ",
    ],
  },
];

export function randomMonster(): Monster {
  return ALL_MONSTERS[Math.floor(Math.random() * ALL_MONSTERS.length)];
}

export function renderMonsterOverlay(
  monster: Monster,
  viewportW: number,
  viewportH: number,
): Array<{ row: number; col: number; text: string }> {
  const sprite = monster.sprite;
  const spriteH = sprite.length;
  const spriteW = Math.max(...sprite.map(s => s.length));
  const scaledW = spriteW * 2;

  // Flying: 8 lines from bottom. Ground: 2 lines from bottom.
  const bottomGap = monster.flying ? 8 : 2;
  const startRow = viewportH - spriteH - bottomGap;
  const startCol = Math.round(viewportW / 2 - scaledW / 2);

  const overlays: Array<{ row: number; col: number; text: string }> = [];

  for (let i = 0; i < spriteH; i++) {
    const row = startRow + i;
    if (row < 0 || row >= viewportH) continue;

    const line = sprite[i];
    let seg = "";
    let segStart = -1;

    for (let j = 0; j <= line.length; j++) {
      const ch = j < line.length ? line[j] : " ";
      const rgb = monster.palette[ch];

      if (rgb) {
        if (segStart < 0) segStart = j;
        seg += `\x1b[48;2;${rgb[0]};${rgb[1]};${rgb[2]}m  `;
      } else {
        if (seg.length > 0) {
          overlays.push({ row, col: startCol + segStart * 2, text: seg + RESET });
          seg = "";
          segStart = -1;
        }
      }
    }
  }

  return overlays;
}

export function renderMonsterStatus(monster: Monster, currentHp: number): string {
  const hpPct = Math.max(0, currentHp / monster.hp);
  const barW = 15;
  const filled = Math.round(hpPct * barW);
  const empty = barW - filled;

  const bar = `\x1b[48;2;50;200;50m${" ".repeat(filled)}\x1b[48;2;60;60;60m${" ".repeat(empty)}${RESET}`;

  const fc = Object.values(monster.palette)[0];
  const nameColor = `\x1b[38;2;${fc[0]};${fc[1]};${fc[2]}m`;

  return `  ${nameColor}${monster.name}${RESET}  HP ${bar} ${currentHp}/${monster.hp}`;
}
